### ISSUE TITLE
Materials problem

### ISSUE THREAD

**Issue by octagonalsquare** [RenolY2/SuperBMD#12]
I get this error while trying to convert from .obj to .bmd with materials and textures
Error encountered while reading BMD\redcoin.mtl
JsonReaderException: Unexpected character encountered while parsing value: #. Path '', line 0, position 0

I had no problem the other day when doing a test conversion. Since then I have actually colored the model correctly and re-exported it with 3ds Max and told it to export the materials too. I did everything the same, and it now doesn't work. I don't know what to make of this. I tried re-exporting multiple times to no avail.

**Comment by RenolY2** [comment]
The material file that this tool supports is not the mtl file that you can export from your 3d modelling format. The kind of material files it supports is .json files that this tool exports when you convert BMDs to DAE, for example
