### ISSUE TITLE
How do i run this thing??

### ISSUE THREAD

**Issue by M3KAI5ER44** [RenolY2/SuperBMD#17]

**Comment by RenolY2** [comment]
Read the readme. If there is something in the readme that is not clear to you then you need to clarify your question.

Compiled releases of the tool can be found here: https://github.com/RenolY2/SuperBMD/releases

**Comment by M3KAI5ER44** [comment]
> To convert a model, drag it onto the executable or run the program via command line:
SuperBMD.exe <model path>> 

What exe I can't see one anywhere!

**Comment by shibbo** [comment]
You get it through the “Releases” tab when you view the repo.

**Comment by M3KAI5ER44** [comment]
Ah- ... i'll... Go check it out...

**Comment by M3KAI5ER44** [comment]
I am an idiot
