### ISSUE TITLE
Scale Problem

### ISSUE THREAD

**Issue by victormr21** [RenolY2/SuperBMD#25]
I'm generating a BMD file using a DAE file, the problem is that when i import it in game (SMG2) it looks huge. To check if it was Game editor's fault, i reimported the generated BMD in Blender (converting to DAE with SuperBMD first) and effectively its scale is a ton bigger.
I've tried generating the BMD with a smaller version of the model but the same, your tool increases its scale a lot.
Do you know why this is happening? Thanks in advance.
PD: I've used your 2 last releases and same

**Comment by FroggoTheDoggo29** [comment]
You never applied the scale in blender. Ctrl-A>Scale

**Comment by victormr21** [comment]
> You never applied the scale in blender. Ctrl-A>Scale

I'm pretty sure I did, bc when I reopen original dae, scale shows fine.
I press S, move the mouse and when it's small I left click, so it applies and I export.

**Comment by FroggoTheDoggo29** [comment]
SuperBMD doesn't read the object scaling. Even if it's in the DAE when you open it in blender, Assimp doesn't interpret it. You need to apply it.
