### ISSUE TITLE
Not converting a .bmd file

### ISSUE THREAD

**Issue by Xrkerr** [RenolY2/SuperBMD#29]
I am completely new to these types of file conversions so I apologise if I am being extremely dumb here.
However, when I try to convert a file with the extension .bmd, the conversion fails and claims the file is not a .bmd file despite its extension. Is there a reason for this? If so, is there a fix or workaround?
![Screenshot (2)](https://user-images.githubusercontent.com/77299628/116982438-b5479e00-acc0-11eb-818c-6ce5ede3272d.png)

**Comment by gayfrogog** [comment]
Can you provide the BMD file? From that filesystem setup, your BMD doesn't seem to be from Nintendo's J3D library, but it's worth taking a look.

**Comment by Xrkerr** [comment]
[dedenne.zip](https://github.com/RenolY2/SuperBMD/files/6420076/dedenne.zip)

**Comment by gayfrogog** [comment]
Hmm, okay, this clearly isn't a J3D model. What game is this from? SuperBMD is explicitly for games utilising the JSYSTEM library, so SMG, SMS, Luigi's Mansion, Twilight Princess, Windwaker, Double Dash, etc are supported.

**Comment by Xrkerr** [comment]
I see, I assumed they would be the same. You can really see how shallow my understanding is with this ahaha.

Its not a Nintendo game so that explains it, its a custom model for MC.
