### ISSUE TITLE
Error while converting a BMD file

### ISSUE THREAD

**Issue by ch3ckyy** [RenolY2/SuperBMD#36]
Hi,
today I tried using your SW to convert some BMD files, got this error

SuperBMD v2.1.0.0

Preparing to convert abomasnow from .BMD to .DAE

Neošetřená výjimka: System.Exception: Model was not a BMD or BDL! (J3D2 magic not found)
   v SuperBMDLib.Model..ctor(EndianBinaryReader reader, Arguments args)
   v SuperBMDLib.Model.Load(Arguments args, List`1 mat_presets, String additionalTexPath)
   v SuperBMDLib.Program.Main(String[] args)

I tried both dragging it on and using the command line, both resulted in the same issue.

**Comment by RenolY2** [comment]
From what game did you get the BMD files from? It might be that your file has the bmd extension but it's not the same bmd format as what this tool supports. This tool is for some of Nintendo's GameCube/Wii era games like Super Mario Sunshine, Pikmin 2 and Super Mario Galaxy.

**Comment by ch3ckyy** [comment]
They´re models from a minecraft mod, I can send you one as an example if that helps you

**Comment by RenolY2** [comment]
Minecraft models are not supported by this tool. Despite the similar file extension, the format itself is completely different.

See issue https://github.com/RenolY2/SuperBMD/issues/29, where somebody else also tried to convert a Minecraft model with this tool.
