### ISSUE TITLE
Every arc file I try just wont work here is error message

### ISSUE THREAD

**Issue by MarioGladiator** [RenolY2/SuperBMD#45]
SuperBMD v2.1.0.0

Preparing to convert Banekiti from .ARC to .BMD

Unhandled Exception: Assimp.AssimpException: Error importing file: No suitable reader found for the file format of file "C:\Users\Test\Downloads\Gamez\DATA\files\ObjectData\Banekiti.arc".
   at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
   at SuperBMDLib.Model.Load(Arguments args, List`1 mat_presets, String additionalTexPath)
   at SuperBMDLib.Program.Main(String[] args)

**Comment by SuperHackio** [comment]
You need to take the BDL/BMD file out of the archive first.

You can do that using [WiiExplorer](https://github.com/SuperHackio/WiiExplorer): Open the .arc with WiiExplorer, then select the BDL/BMD file and right click > Export (or use right click to drag the file out to your desktop or to a folder)

Once it's extracted you can use SuperBMD to dump it to the .dae format and then load that into a modeling program (like Blender)
