### ISSUE TITLE
SM64DS BMD: Model was not a BMD or BDL! (J3D2 magic not found)

### ISSUE THREAD

**Issue by axel7083** [RenolY2/SuperBMD#51]
Extracting the `main_castle_all.bmd` in the SM64DS rom, and using the tool on it. Here the logs:

```
Preparing to convert main_castle_all from .BMD to .DAE

Exception non gérée : System.Exception: Model was not a BMD or BDL! (J3D2 magic not found)
   à SuperBMDLib.Model..ctor(EndianBinaryReader reader, Arguments args)
   à SuperBMDLib.Model.Load(Arguments args, List`1 mat_presets, String additionalTexPath)
   à SuperBMDLib.Program.Main(String[] args)
```

## How to get the model

- Get a cleaned SM64DS rom
- Using any filesystem compatible ([SM64DSe-Ultimate](https://github.com/Gota7/SM64DSe-Ultimate)) extract `data/stage/main_castle/main_castle_all.bmd` (raw)

**Comment by RenolY2** [comment]
SM64DS BMD files are entirely different from the BMD files supported by SuperBMD. SuperBMD only supports BMD files found on some GameCube games like Super Mario Sunshine and Mario Kart Double Dash.

For BMD files found in DS games you want to look for DS-specific tools, e.g. https://github.com/scurest/apicula

**Comment by axel7083** [comment]
Oh, wonderful, thanks nintendo for calling them the same !
Closing as not linked to the repository
